import type { UserRole, PermissionString } from './types'

export const ROLE_HIERARCHY: Record<UserRole, number> = {
  OWNER: 100,
  ADMIN: 80,
  TEAM_LEAD: 60,
  DEVELOPER: 40,
  VIEWER: 20,
}

export const PERMISSION_MATRIX: Record<UserRole, PermissionString[]> = {
  OWNER: ['*'],
  ADMIN: [
    'organization:view',
    'organization:edit',
    'members:view',
    'members:create',
    'members:edit',
    'members:delete',
    'members:assign',
    'teams:view',
    'teams:create',
    'teams:edit',
    'teams:delete',
    'teams:manage',
    'projects:view',
    'projects:create',
    'projects:edit',
    'projects:delete',
    'sprints:view',
    'sprints:create',
    'sprints:edit',
    'sprints:delete',
    'releases:view',
    'releases:create',
    'releases:edit',
    'releases:delete',
    'metrics:view',
    'metrics:export',
    'audit:view',
    'audit:export',
    'settings:view',
    'settings:edit',
    'integrations:view',
    'integrations:edit',
    'onboarding:view',
    'onboarding:manage',
    'reviews:view',
    'goals:view',
    'goals:create',
    'goals:edit',
    'goals:delete',
    'reports:view',
    'reports:create',
    'alerts:view',
    'alerts:manage',
    'debt:view',
    'debt:manage',
  ],
  TEAM_LEAD: [
    'organization:view',
    'members:view',
    'teams:view:team',
    'teams:edit:team',
    'projects:view',
    'projects:create',
    'projects:edit',
    'sprints:view',
    'sprints:create',
    'sprints:edit',
    'metrics:view',
    'metrics:export',
    'settings:view',
    'onboarding:view',
    'onboarding:manage',
    'reviews:view',
    'goals:view',
    'goals:create',
    'goals:edit',
    'reports:view',
    'reports:create',
    'alerts:view',
    'debt:view',
    'debt:manage',
  ],
  DEVELOPER: [
    'organization:view',
    'members:view',
    'teams:view',
    'projects:view',
    'sprints:view',
    'metrics:view:own',
    'metrics:view:team',
    'reviews:view',
    'goals:view',
    'reports:view',
    'alerts:view',
    'debt:view',
  ],
  VIEWER: [
    'organization:view',
    'members:view',
    'teams:view',
    'projects:view',
    'sprints:view',
    'metrics:view',
    'reviews:view',
    'goals:view',
    'reports:view',
  ],
}

export function hasRoleLevel(userRole: UserRole, requiredRole: UserRole): boolean {
  const userLevel = ROLE_HIERARCHY[userRole] ?? 0
  const requiredLevel = ROLE_HIERARCHY[requiredRole] ?? 0
  return userLevel >= requiredLevel
}
